AWSTemplateFormatVersion: 2010-09-09
Description: network resources for apis.goldenbearkin.com
Parameters:
  DomainName:
    Type: String
    Description: The site domain name (e.g. example.com)
  SubDomainName:
    Type: String
    Description: The site sub-domain name (e.g. www)
  AcmCertificateArn:
    Type: String
Resources:
  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub ${SubDomainName}.${DomainName}
      CertificateArn: !Ref AcmCertificateArn
  ApiDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      RecordSets:
      - 
        Name: !Sub ${SubDomainName}.${DomainName}.
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt 
            - ApiDomainName
            - DistributionDomainName
Outputs:
  domainName:
    Value: !GetAtt 
      - ApiDomainName
      - DistributionDomainName